/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adv_of_code_2023

import kotlin.test.Test
import kotlin.test.assertNotNull

class Day1Test {
    @Test fun appHasAGreeting() {
        val classUnderTest = Day1()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
